version: '3.8'

services:
  mariadb:
    container_name: IPRWC-Databace
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: TotallyHackable
      MARIADB_DATABASE: IPRWC
    ports:
      - "6033:3306"

